// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mosque struct {
	ID         pgtype.UUID      `json:"id"`
	Name       string           `json:"name"`
	Address    string           `json:"address"`
	EidTime    pgtype.Timestamp `json:"eid_time"`
	JummahTime pgtype.Timestamp `json:"jummah_time"`
	Lat        pgtype.Numeric   `json:"lat"`
	Lng        pgtype.Numeric   `json:"lng"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
