// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateMosque(ctx context.Context, arg CreateMosqueParams) (Mosque, error)
	GetAllMosque(ctx context.Context) ([]Mosque, error)
	GetUMosqueByName(ctx context.Context, name string) (Mosque, error)
	UpdateMosque(ctx context.Context, arg UpdateMosqueParams) (Mosque, error)
}

var _ Querier = (*Queries)(nil)
